# Project Name
TARGET = main

# Sources
# IMPORTANT: List all your .cpp files here, separated by spaces
CPP_SOURCES = main.cpp XorM.cpp

# Library Locations
LIBDAISY_DIR = ../../libs/libDaisy
DAISYSP_DIR = ../../libs/DaisySP

# Core location and generic Makefile inclusion
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile